name: Publish Package

on:
  release:
    types:
      - published

jobs:
  publish:
    environment: pypi

    permissions:
      id-token: write

    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      PYTHON_VERSION: 3.9

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry

      - name: Build
        run: |
          poetry version ${{ github.ref_name }}
          poetry build
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
